### ISSUE TITLE
vendor-federal-de: updated columns, added cities

### ISSUE THREAD

**Issue by robbi5** [benbalter/gman#130]
Hi,

I just updated the [german-gov-domains](https://github.com/robbi5/german-gov-domains) list to use the same columns as the [dotgov domains from gsa/data](https://github.com/GSA/data). The full list contains cities now, but a [federal domains only subset](https://github.com/robbi5/german-gov-domains/blob/master/data/domains.federal.csv) is available too.

**Comment by akuckartz** [comment]
:+1:

**Comment by jbjonesjr** [comment]
bot fight!!
