### ISSUE TITLE
No domains of German municipalities ?

### ISSUE THREAD

**Issue by akuckartz** [benbalter/gman#74]
The list of domains does not seem to contain any domain controlled by a German municipality. I am in particular missing `stadt-koeln.de`

**Comment by benbalter** [comment]
@akuckartz is there a list of those domains? If not, would you be able to compile one? Would love to get them added.

**Comment by akuckartz** [comment]
@benbalter I think that such lists are available for some of the German states. I will have a look. They might be useful open data.

**Comment by akuckartz** [comment]
The state of North Rhine-Westphalia publishes a list of its municipalities:
http://www.mik.nrw.de/nc/themen-aufgaben/kommunales/kommunale-adressen.html

Note the link "Export als CSV-Datei" below the table.

**Comment by benbalter** [comment]
@akuckartz Made a script to vendor the domains listed in the CSV over in https://github.com/benbalter/gman/pull/76.

To confirm, those are all government domains, correct?

Also, do any other states have similar lists that you know of?

**Comment by akuckartz** [comment]
Thanks for the very quick reaction!

Yes, the list is maintained by the Ministry of Interior of North Rhine-Westphalia and they claim that these domains all belong to municipalities. Knowing German public administration bureacracy I suppose that this claim is correct.

I will provide further lists when I find them.

**Comment by akuckartz** [comment]
An official source for domains of municipalities in Brandenburg:
http://service.brandenburg.de/lis/list.php?page=kommunen_p

Unfortunately it is not meant for machines :-(

I will attempt to find an unofficial machine-readable list but that will take more time.
