### ISSUE TITLE
Add german domains / more municipalities

### ISSUE THREAD

**Issue by step21** [benbalter/gman#86]
German Gov domains are missing from what I can tell, municipalities seem only to be present from one of sixteen states. :)

**Comment by benbalter** [comment]
@step21 do you know of any machine-readable lists of domains (ideally published by a government agency)? The municipality domains are vendored via https://github.com/benbalter/gman/blob/master/script/vendor-de, and you can see some context via https://github.com/benbalter/gman/issues/74, but I'd love to add more.
